export enum Permission {
  // Orders
  VIEW_ORDERS = "VIEW_ORDERS",
  CREATE_ORDERS = "CREATE_ORDERS",
  CONFIRM_ORDERS = "CONFIRM_ORDERS",
  CANCEL_ORDERS = "CANCEL_ORDERS",

  // Assets
  VIEW_ASSETS = "VIEW_ASSETS",
  CREATE_ASSETS = "CREATE_ASSETS",
  UPDATE_ASSETS = "UPDATE_ASSETS",
  DELETE_ASSETS = "DELETE_ASSETS",

  // Asset Assignments
  VIEW_ASSET_ASSIGNMENTS = "VIEW_ASSET_ASSIGNMENTS",
  MANAGE_ASSET_ASSIGNMENTS = "MANAGE_ASSET_ASSIGNMENTS",

  // Products
  VIEW_PRODUCTS = "VIEW_PRODUCTS",
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  UPDATE_PRODUCTS = "UPDATE_PRODUCTS",
  DELETE_PRODUCTS = "DELETE_PRODUCTS",

  // Bundles
  VIEW_BUNDLES = "VIEW_BUNDLES",
  MANAGE_BUNDLES = "MANAGE_BUNDLES",

  // Pricing
  VIEW_PRICING = "VIEW_PRICING",
  MANAGE_PRICING = "MANAGE_PRICING",

  // Customers
  VIEW_CUSTOMERS = "VIEW_CUSTOMERS",
  MANAGE_CUSTOMERS = "MANAGE_CUSTOMERS",

  // Owners
  VIEW_OWNERS = "VIEW_OWNERS",
  MANAGE_OWNERS = "MANAGE_OWNERS",

  // Locations
  VIEW_LOCATIONS = "VIEW_LOCATIONS",
  MANAGE_LOCATIONS = "MANAGE_LOCATIONS",

  // Users & Roles
  VIEW_USERS = "VIEW_USERS",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_ROLES = "MANAGE_ROLES",
  INVITE_USERS = "INVITE_USERS",
}
