export enum PromotionActivationType {
  AUTOMATIC = "AUTOMATIC",
  COUPON = "COUPON",
}

export enum PromotionStackingType {
  EXCLUSIVE = "EXCLUSIVE",
  COMBINABLE = "COMBINABLE",
}

export enum PromotionApplicabilityTarget {
  PRODUCT = "PRODUCT",
  BUNDLE = "BUNDLE",
}

export enum PromotionConditionType {
  BOOKING_WINDOW = "BOOKING_WINDOW",
  RENTAL_WINDOW = "RENTAL_WINDOW",
  CUSTOMER_ID_IN = "CUSTOMER_ID_IN",
  MIN_SUBTOTAL = "MIN_SUBTOTAL",
  RENTAL_DURATION_MIN = "RENTAL_DURATION_MIN",
  MIN_PRODUCT_QUANTITY = "MIN_PRODUCT_QUANTITY",
  MIN_PRODUCT_UNIT_PRICE = "MIN_PRODUCT_UNIT_PRICE",
}

export enum PromotionEffectType {
  PERCENT_OFF = "PERCENT_OFF",
  LONG_RENTAL_TIERED_PERCENT_OFF = "LONG_RENTAL_TIERED_PERCENT_OFF",
}
