/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiCustomerUploadRouteImport } from './routes/api/customer-upload'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as CustomerRentalIndexRouteImport } from './routes/_customer/rental/index'
import { Route as CustomerOrderConfirmationIndexRouteImport } from './routes/_customer/order-confirmation/index'
import { Route as CustomerOnboardIndexRouteImport } from './routes/_customer/onboard/index'
import { Route as CustomerCartIndexRouteImport } from './routes/_customer/cart/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AdminAdminRegisterRouteImport } from './routes/_admin/admin/register'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as AdminDashboardScheduleIndexRouteImport } from './routes/_admin/dashboard/schedule/index'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardLocationsIndexRouteImport } from './routes/_admin/dashboard/locations/index'
import { Route as AdminDashboardOrdersOrderIdRouteImport } from './routes/_admin/dashboard/orders/$orderId'
import { Route as AdminDashboardInventoryAssetsIndexRouteImport } from './routes/_admin/dashboard/inventory/assets/index'
import { Route as AdminDashboardCatalogProductsIndexRouteImport } from './routes/_admin/dashboard/catalog/products/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogBundlesIndexRouteImport } from './routes/_admin/dashboard/catalog/bundles/index'
import { Route as AdminDashboardCatalogProductsNewRouteImport } from './routes/_admin/dashboard/catalog/products/new'
import { Route as AdminDashboardCatalogProductsProductIdRouteImport } from './routes/_admin/dashboard/catalog/products/$productId'
import { Route as AdminDashboardCatalogBundlesNewRouteImport } from './routes/_admin/dashboard/catalog/bundles/new'
import { Route as AdminDashboardCatalogBundlesBundleIdRouteImport } from './routes/_admin/dashboard/catalog/bundles/$bundleId'

const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerUploadRoute = ApiCustomerUploadRouteImport.update({
  id: '/api/customer-upload',
  path: '/api/customer-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRentalIndexRoute = CustomerRentalIndexRouteImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrderConfirmationIndexRoute =
  CustomerOrderConfirmationIndexRouteImport.update({
    id: '/order-confirmation/',
    path: '/order-confirmation/',
    getParentRoute: () => CustomerRoute,
  } as any)
const CustomerOnboardIndexRoute = CustomerOnboardIndexRouteImport.update({
  id: '/onboard/',
  path: '/onboard/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartIndexRoute = CustomerCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminAdminRegisterRoute = AdminAdminRegisterRouteImport.update({
  id: '/_admin/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/_admin/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardScheduleIndexRoute =
  AdminDashboardScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsIndexRoute =
  AdminDashboardLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdRoute =
  AdminDashboardOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryAssetsIndexRoute =
  AdminDashboardInventoryAssetsIndexRouteImport.update({
    id: '/inventory/assets/',
    path: '/inventory/assets/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsIndexRoute =
  AdminDashboardCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesIndexRoute =
  AdminDashboardCatalogBundlesIndexRouteImport.update({
    id: '/catalog/bundles/',
    path: '/catalog/bundles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsNewRoute =
  AdminDashboardCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsProductIdRoute =
  AdminDashboardCatalogProductsProductIdRouteImport.update({
    id: '/catalog/products/$productId',
    path: '/catalog/products/$productId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesNewRoute =
  AdminDashboardCatalogBundlesNewRouteImport.update({
    id: '/catalog/bundles/new',
    path: '/catalog/bundles/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesBundleIdRoute =
  AdminDashboardCatalogBundlesBundleIdRouteImport.update({
    id: '/catalog/bundles/$bundleId',
    path: '/catalog/bundles/$bundleId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/cart/': typeof CustomerCartIndexRoute
  '/onboard/': typeof CustomerOnboardIndexRoute
  '/order-confirmation/': typeof CustomerOrderConfirmationIndexRoute
  '/rental/': typeof CustomerRentalIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/catalog/bundles/$bundleId': typeof AdminDashboardCatalogBundlesBundleIdRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/products/$productId': typeof AdminDashboardCatalogProductsProductIdRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/cart': typeof CustomerCartIndexRoute
  '/onboard': typeof CustomerOnboardIndexRoute
  '/order-confirmation': typeof CustomerOrderConfirmationIndexRoute
  '/rental': typeof CustomerRentalIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/dashboard/locations': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/schedule': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/catalog/bundles/$bundleId': typeof AdminDashboardCatalogBundlesBundleIdRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/products/$productId': typeof AdminDashboardCatalogProductsProductIdRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/catalog/bundles': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/inventory/assets': typeof AdminDashboardInventoryAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_customer': typeof CustomerRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/register': typeof AdminAdminRegisterRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_customer/cart/': typeof CustomerCartIndexRoute
  '/_customer/onboard/': typeof CustomerOnboardIndexRoute
  '/_customer/order-confirmation/': typeof CustomerOrderConfirmationIndexRoute
  '/_customer/rental/': typeof CustomerRentalIndexRoute
  '/_admin/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/_admin/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_admin/dashboard/catalog/bundles/$bundleId': typeof AdminDashboardCatalogBundlesBundleIdRoute
  '/_admin/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/_admin/dashboard/catalog/products/$productId': typeof AdminDashboardCatalogProductsProductIdRoute
  '/_admin/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/_admin/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/_admin/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/dashboard/'
    | '/cart/'
    | '/onboard/'
    | '/order-confirmation/'
    | '/rental/'
    | '/dashboard/orders/$orderId'
    | '/dashboard/locations/'
    | '/dashboard/owners/'
    | '/dashboard/schedule/'
    | '/dashboard/settings/'
    | '/dashboard/catalog/bundles/$bundleId'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/products/$productId'
    | '/dashboard/catalog/products/new'
    | '/dashboard/catalog/bundles/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/catalog/products/'
    | '/dashboard/inventory/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/dashboard'
    | '/cart'
    | '/onboard'
    | '/order-confirmation'
    | '/rental'
    | '/dashboard/orders/$orderId'
    | '/dashboard/locations'
    | '/dashboard/owners'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/catalog/bundles/$bundleId'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/products/$productId'
    | '/dashboard/catalog/products/new'
    | '/dashboard/catalog/bundles'
    | '/dashboard/catalog/categories'
    | '/dashboard/catalog/products'
    | '/dashboard/inventory/assets'
  id:
    | '__root__'
    | '/'
    | '/_customer'
    | '/_admin/dashboard'
    | '/api/customer-upload'
    | '/api/upload'
    | '/_admin/admin/login'
    | '/_admin/admin/register'
    | '/_admin/dashboard/'
    | '/_customer/cart/'
    | '/_customer/onboard/'
    | '/_customer/order-confirmation/'
    | '/_customer/rental/'
    | '/_admin/dashboard/orders/$orderId'
    | '/_admin/dashboard/locations/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/schedule/'
    | '/_admin/dashboard/settings/'
    | '/_admin/dashboard/catalog/bundles/$bundleId'
    | '/_admin/dashboard/catalog/bundles/new'
    | '/_admin/dashboard/catalog/products/$productId'
    | '/_admin/dashboard/catalog/products/new'
    | '/_admin/dashboard/catalog/bundles/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/catalog/products/'
    | '/_admin/dashboard/inventory/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  ApiCustomerUploadRoute: typeof ApiCustomerUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminRegisterRoute: typeof AdminAdminRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-upload': {
      id: '/api/customer-upload'
      path: '/api/customer-upload'
      fullPath: '/api/customer-upload'
      preLoaderRoute: typeof ApiCustomerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/rental/': {
      id: '/_customer/rental/'
      path: '/rental'
      fullPath: '/rental/'
      preLoaderRoute: typeof CustomerRentalIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/order-confirmation/': {
      id: '/_customer/order-confirmation/'
      path: '/order-confirmation'
      fullPath: '/order-confirmation/'
      preLoaderRoute: typeof CustomerOrderConfirmationIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/onboard/': {
      id: '/_customer/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof CustomerOnboardIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/cart/': {
      id: '/_customer/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CustomerCartIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/admin/register': {
      id: '/_admin/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminAdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/schedule/': {
      id: '/_admin/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule/'
      preLoaderRoute: typeof AdminDashboardScheduleIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/': {
      id: '/_admin/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof AdminDashboardLocationsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId': {
      id: '/_admin/dashboard/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/assets/': {
      id: '/_admin/dashboard/inventory/assets/'
      path: '/inventory/assets'
      fullPath: '/dashboard/inventory/assets/'
      preLoaderRoute: typeof AdminDashboardInventoryAssetsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/': {
      id: '/_admin/dashboard/catalog/products/'
      path: '/catalog/products'
      fullPath: '/dashboard/catalog/products/'
      preLoaderRoute: typeof AdminDashboardCatalogProductsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/': {
      id: '/_admin/dashboard/catalog/bundles/'
      path: '/catalog/bundles'
      fullPath: '/dashboard/catalog/bundles/'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/new': {
      id: '/_admin/dashboard/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/dashboard/catalog/products/new'
      preLoaderRoute: typeof AdminDashboardCatalogProductsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/$productId': {
      id: '/_admin/dashboard/catalog/products/$productId'
      path: '/catalog/products/$productId'
      fullPath: '/dashboard/catalog/products/$productId'
      preLoaderRoute: typeof AdminDashboardCatalogProductsProductIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/new': {
      id: '/_admin/dashboard/catalog/bundles/new'
      path: '/catalog/bundles/new'
      fullPath: '/dashboard/catalog/bundles/new'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/$bundleId': {
      id: '/_admin/dashboard/catalog/bundles/$bundleId'
      path: '/catalog/bundles/$bundleId'
      fullPath: '/dashboard/catalog/bundles/$bundleId'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesBundleIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerCartIndexRoute: typeof CustomerCartIndexRoute
  CustomerOnboardIndexRoute: typeof CustomerOnboardIndexRoute
  CustomerOrderConfirmationIndexRoute: typeof CustomerOrderConfirmationIndexRoute
  CustomerRentalIndexRoute: typeof CustomerRentalIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartIndexRoute: CustomerCartIndexRoute,
  CustomerOnboardIndexRoute: CustomerOnboardIndexRoute,
  CustomerOrderConfirmationIndexRoute: CustomerOrderConfirmationIndexRoute,
  CustomerRentalIndexRoute: CustomerRentalIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardOrdersOrderIdRoute: typeof AdminDashboardOrdersOrderIdRoute
  AdminDashboardLocationsIndexRoute: typeof AdminDashboardLocationsIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardScheduleIndexRoute: typeof AdminDashboardScheduleIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardCatalogBundlesBundleIdRoute: typeof AdminDashboardCatalogBundlesBundleIdRoute
  AdminDashboardCatalogBundlesNewRoute: typeof AdminDashboardCatalogBundlesNewRoute
  AdminDashboardCatalogProductsProductIdRoute: typeof AdminDashboardCatalogProductsProductIdRoute
  AdminDashboardCatalogProductsNewRoute: typeof AdminDashboardCatalogProductsNewRoute
  AdminDashboardCatalogBundlesIndexRoute: typeof AdminDashboardCatalogBundlesIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCatalogProductsIndexRoute: typeof AdminDashboardCatalogProductsIndexRoute
  AdminDashboardInventoryAssetsIndexRoute: typeof AdminDashboardInventoryAssetsIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardOrdersOrderIdRoute: AdminDashboardOrdersOrderIdRoute,
  AdminDashboardLocationsIndexRoute: AdminDashboardLocationsIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardScheduleIndexRoute: AdminDashboardScheduleIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardCatalogBundlesBundleIdRoute:
    AdminDashboardCatalogBundlesBundleIdRoute,
  AdminDashboardCatalogBundlesNewRoute: AdminDashboardCatalogBundlesNewRoute,
  AdminDashboardCatalogProductsProductIdRoute:
    AdminDashboardCatalogProductsProductIdRoute,
  AdminDashboardCatalogProductsNewRoute: AdminDashboardCatalogProductsNewRoute,
  AdminDashboardCatalogBundlesIndexRoute:
    AdminDashboardCatalogBundlesIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCatalogProductsIndexRoute:
    AdminDashboardCatalogProductsIndexRoute,
  AdminDashboardInventoryAssetsIndexRoute:
    AdminDashboardInventoryAssetsIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  ApiCustomerUploadRoute: ApiCustomerUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminRegisterRoute: AdminAdminRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
