/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiCustomerUploadRouteImport } from './routes/api/customer-upload'
import { Route as ApiBrandingUploadRouteImport } from './routes/api/branding-upload'
import { Route as PortalRegisterRouteImport } from './routes/_portal/register'
import { Route as PortalLoginRouteImport } from './routes/_portal/login'
import { Route as PortalTenantRouteRouteImport } from './routes/_portal/_tenant/route'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AdminAdminRegisterRouteImport } from './routes/_admin/admin/register'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as PortalTenantRentalIndexRouteImport } from './routes/_portal/_tenant/rental/index'
import { Route as PortalTenantOrderConfirmationIndexRouteImport } from './routes/_portal/_tenant/order-confirmation/index'
import { Route as PortalTenantOnboardIndexRouteImport } from './routes/_portal/_tenant/onboard/index'
import { Route as PortalTenantCartIndexRouteImport } from './routes/_portal/_tenant/cart/index'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as AdminDashboardScheduleIndexRouteImport } from './routes/_admin/dashboard/schedule/index'
import { Route as AdminDashboardPromotionsIndexRouteImport } from './routes/_admin/dashboard/promotions/index'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/_admin/dashboard/orders/index'
import { Route as AdminDashboardLocationsIndexRouteImport } from './routes/_admin/dashboard/locations/index'
import { Route as AdminDashboardCustomersIndexRouteImport } from './routes/_admin/dashboard/customers/index'
import { Route as ApiOrdersOrderIdContractRouteImport } from './routes/api/orders/$orderId/contract'
import { Route as ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport } from './routes/api/customer-profiles/$customerProfileId/identity-document'
import { Route as PortalAuthGoogleFinalizeRouteImport } from './routes/_portal/auth/google/finalize'
import { Route as AdminDashboardPromotionsNewRouteImport } from './routes/_admin/dashboard/promotions/new'
import { Route as AdminDashboardOwnersOwnerIdRouteImport } from './routes/_admin/dashboard/owners/$ownerId'
import { Route as AdminDashboardOrdersOrderIdRouteImport } from './routes/_admin/dashboard/orders/$orderId'
import { Route as AdminDashboardLocationsLocationIdRouteImport } from './routes/_admin/dashboard/locations/$locationId'
import { Route as AdminDashboardCustomersCustomerIdRouteImport } from './routes/_admin/dashboard/customers/$customerId'
import { Route as AdminDashboardInventoryAssetsIndexRouteImport } from './routes/_admin/dashboard/inventory/assets/index'
import { Route as AdminDashboardCustomersPendingProfilesIndexRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/index'
import { Route as AdminDashboardCatalogProductsIndexRouteImport } from './routes/_admin/dashboard/catalog/products/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogBundlesIndexRouteImport } from './routes/_admin/dashboard/catalog/bundles/index'
import { Route as ApiOrdersOrderIdContractDownloadRouteImport } from './routes/api/orders/$orderId/contract/download'
import { Route as AdminDashboardPromotionsPromotionIdEditRouteImport } from './routes/_admin/dashboard/promotions/$promotionId/edit'
import { Route as AdminDashboardCustomersPendingProfilesCustomerProfileIdRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/$customerProfileId'
import { Route as AdminDashboardCatalogProductsNewRouteImport } from './routes/_admin/dashboard/catalog/products/new'
import { Route as AdminDashboardCatalogBundlesNewRouteImport } from './routes/_admin/dashboard/catalog/bundles/new'
import { Route as AdminDashboardCatalogProductsProductIdIndexRouteImport } from './routes/_admin/dashboard/catalog/products/$productId/index'
import { Route as AdminDashboardCatalogBundlesBundleIdIndexRouteImport } from './routes/_admin/dashboard/catalog/bundles/$bundleId/index'
import { Route as AdminDashboardCatalogProductsProductIdEditRouteImport } from './routes/_admin/dashboard/catalog/products/$productId/edit'
import { Route as AdminDashboardCatalogBundlesBundleIdEditRouteImport } from './routes/_admin/dashboard/catalog/bundles/$bundleId/edit'

const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerUploadRoute = ApiCustomerUploadRouteImport.update({
  id: '/api/customer-upload',
  path: '/api/customer-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingUploadRoute = ApiBrandingUploadRouteImport.update({
  id: '/api/branding-upload',
  path: '/api/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTenantRouteRoute = PortalTenantRouteRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRegisterRoute = AdminAdminRegisterRouteImport.update({
  id: '/_admin/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/_admin/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTenantRentalIndexRoute = PortalTenantRentalIndexRouteImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => PortalTenantRouteRoute,
} as any)
const PortalTenantOrderConfirmationIndexRoute =
  PortalTenantOrderConfirmationIndexRouteImport.update({
    id: '/order-confirmation/',
    path: '/order-confirmation/',
    getParentRoute: () => PortalTenantRouteRoute,
  } as any)
const PortalTenantOnboardIndexRoute =
  PortalTenantOnboardIndexRouteImport.update({
    id: '/onboard/',
    path: '/onboard/',
    getParentRoute: () => PortalTenantRouteRoute,
  } as any)
const PortalTenantCartIndexRoute = PortalTenantCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => PortalTenantRouteRoute,
} as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardScheduleIndexRoute =
  AdminDashboardScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsIndexRoute =
  AdminDashboardPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsIndexRoute =
  AdminDashboardLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersIndexRoute =
  AdminDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractRoute =
  ApiOrdersOrderIdContractRouteImport.update({
    id: '/api/orders/$orderId/contract',
    path: '/api/orders/$orderId/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute =
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport.update({
    id: '/api/customer-profiles/$customerProfileId/identity-document',
    path: '/api/customer-profiles/$customerProfileId/identity-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalAuthGoogleFinalizeRoute =
  PortalAuthGoogleFinalizeRouteImport.update({
    id: '/auth/google/finalize',
    path: '/auth/google/finalize',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const AdminDashboardPromotionsNewRoute =
  AdminDashboardPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersOwnerIdRoute =
  AdminDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdRoute =
  AdminDashboardOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsLocationIdRoute =
  AdminDashboardLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersCustomerIdRoute =
  AdminDashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryAssetsIndexRoute =
  AdminDashboardInventoryAssetsIndexRouteImport.update({
    id: '/inventory/assets/',
    path: '/inventory/assets/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesIndexRoute =
  AdminDashboardCustomersPendingProfilesIndexRouteImport.update({
    id: '/customers/pending-profiles/',
    path: '/customers/pending-profiles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsIndexRoute =
  AdminDashboardCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesIndexRoute =
  AdminDashboardCatalogBundlesIndexRouteImport.update({
    id: '/catalog/bundles/',
    path: '/catalog/bundles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractDownloadRoute =
  ApiOrdersOrderIdContractDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdContractRoute,
  } as any)
const AdminDashboardPromotionsPromotionIdEditRoute =
  AdminDashboardPromotionsPromotionIdEditRouteImport.update({
    id: '/promotions/$promotionId/edit',
    path: '/promotions/$promotionId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute =
  AdminDashboardCustomersPendingProfilesCustomerProfileIdRouteImport.update({
    id: '/customers/pending-profiles/$customerProfileId',
    path: '/customers/pending-profiles/$customerProfileId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsNewRoute =
  AdminDashboardCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesNewRoute =
  AdminDashboardCatalogBundlesNewRouteImport.update({
    id: '/catalog/bundles/new',
    path: '/catalog/bundles/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsProductIdIndexRoute =
  AdminDashboardCatalogProductsProductIdIndexRouteImport.update({
    id: '/catalog/products/$productId/',
    path: '/catalog/products/$productId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesBundleIdIndexRoute =
  AdminDashboardCatalogBundlesBundleIdIndexRouteImport.update({
    id: '/catalog/bundles/$bundleId/',
    path: '/catalog/bundles/$bundleId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsProductIdEditRoute =
  AdminDashboardCatalogProductsProductIdEditRouteImport.update({
    id: '/catalog/products/$productId/edit',
    path: '/catalog/products/$productId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesBundleIdEditRoute =
  AdminDashboardCatalogBundlesBundleIdEditRouteImport.update({
    id: '/catalog/bundles/$bundleId/edit',
    path: '/catalog/bundles/$bundleId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/login': typeof PortalLoginRoute
  '/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/cart/': typeof PortalTenantCartIndexRoute
  '/onboard/': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/rental/': typeof PortalTenantRentalIndexRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/customers/pending-profiles/$customerProfileId': typeof AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
  '/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/dashboard/catalog/bundles/$bundleId/': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/dashboard/catalog/products/$productId/': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PortalLoginRoute
  '/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/customers': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/locations': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/schedule': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/cart': typeof PortalTenantCartIndexRoute
  '/onboard': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation': typeof PortalTenantOrderConfirmationIndexRoute
  '/rental': typeof PortalTenantRentalIndexRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/customers/pending-profiles/$customerProfileId': typeof AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/dashboard/catalog/bundles': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/customers/pending-profiles': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/assets': typeof AdminDashboardInventoryAssetsIndexRoute
  '/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/dashboard/catalog/bundles/$bundleId': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/dashboard/catalog/products/$productId': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/_portal/_tenant': typeof PortalTenantRouteRouteWithChildren
  '/_portal/login': typeof PortalLoginRoute
  '/_portal/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/_admin/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/_admin/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdRoute
  '/_admin/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/_admin/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/_portal/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/_admin/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/_admin/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/_admin/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/_admin/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_portal/_tenant/cart/': typeof PortalTenantCartIndexRoute
  '/_portal/_tenant/onboard/': typeof PortalTenantOnboardIndexRoute
  '/_portal/_tenant/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/_portal/_tenant/rental/': typeof PortalTenantRentalIndexRoute
  '/_admin/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/_admin/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/_admin/dashboard/customers/pending-profiles/$customerProfileId': typeof AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute
  '/_admin/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/_admin/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/_admin/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/_admin/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
  '/_admin/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/_admin/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/_admin/dashboard/catalog/bundles/$bundleId/': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/_admin/dashboard/catalog/products/$productId/': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dashboard/'
    | '/dashboard/customers/$customerId'
    | '/dashboard/locations/$locationId'
    | '/dashboard/orders/$orderId'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/orders/$orderId/contract'
    | '/dashboard/customers/'
    | '/dashboard/locations/'
    | '/dashboard/orders/'
    | '/dashboard/owners/'
    | '/dashboard/promotions/'
    | '/dashboard/schedule/'
    | '/dashboard/settings/'
    | '/cart/'
    | '/onboard/'
    | '/order-confirmation/'
    | '/rental/'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/products/new'
    | '/dashboard/customers/pending-profiles/$customerProfileId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/dashboard/catalog/bundles/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/catalog/products/'
    | '/dashboard/customers/pending-profiles/'
    | '/dashboard/inventory/assets/'
    | '/dashboard/catalog/bundles/$bundleId/edit'
    | '/dashboard/catalog/products/$productId/edit'
    | '/dashboard/catalog/bundles/$bundleId/'
    | '/dashboard/catalog/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dashboard'
    | '/dashboard/customers/$customerId'
    | '/dashboard/locations/$locationId'
    | '/dashboard/orders/$orderId'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/orders/$orderId/contract'
    | '/dashboard/customers'
    | '/dashboard/locations'
    | '/dashboard/orders'
    | '/dashboard/owners'
    | '/dashboard/promotions'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/cart'
    | '/onboard'
    | '/order-confirmation'
    | '/rental'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/products/new'
    | '/dashboard/customers/pending-profiles/$customerProfileId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/dashboard/catalog/bundles'
    | '/dashboard/catalog/categories'
    | '/dashboard/catalog/products'
    | '/dashboard/customers/pending-profiles'
    | '/dashboard/inventory/assets'
    | '/dashboard/catalog/bundles/$bundleId/edit'
    | '/dashboard/catalog/products/$productId/edit'
    | '/dashboard/catalog/bundles/$bundleId'
    | '/dashboard/catalog/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/_admin/dashboard'
    | '/_portal/_tenant'
    | '/_portal/login'
    | '/_portal/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/_admin/admin/login'
    | '/_admin/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/customers/$customerId'
    | '/_admin/dashboard/locations/$locationId'
    | '/_admin/dashboard/orders/$orderId'
    | '/_admin/dashboard/owners/$ownerId'
    | '/_admin/dashboard/promotions/new'
    | '/_portal/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/orders/$orderId/contract'
    | '/_admin/dashboard/customers/'
    | '/_admin/dashboard/locations/'
    | '/_admin/dashboard/orders/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/promotions/'
    | '/_admin/dashboard/schedule/'
    | '/_admin/dashboard/settings/'
    | '/_portal/_tenant/cart/'
    | '/_portal/_tenant/onboard/'
    | '/_portal/_tenant/order-confirmation/'
    | '/_portal/_tenant/rental/'
    | '/_admin/dashboard/catalog/bundles/new'
    | '/_admin/dashboard/catalog/products/new'
    | '/_admin/dashboard/customers/pending-profiles/$customerProfileId'
    | '/_admin/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/_admin/dashboard/catalog/bundles/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/catalog/products/'
    | '/_admin/dashboard/customers/pending-profiles/'
    | '/_admin/dashboard/inventory/assets/'
    | '/_admin/dashboard/catalog/bundles/$bundleId/edit'
    | '/_admin/dashboard/catalog/products/$productId/edit'
    | '/_admin/dashboard/catalog/bundles/$bundleId/'
    | '/_admin/dashboard/catalog/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  ApiBrandingUploadRoute: typeof ApiBrandingUploadRoute
  ApiCustomerUploadRoute: typeof ApiCustomerUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminRegisterRoute: typeof AdminAdminRegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  ApiOrdersOrderIdContractRoute: typeof ApiOrdersOrderIdContractRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-upload': {
      id: '/api/customer-upload'
      path: '/api/customer-upload'
      fullPath: '/api/customer-upload'
      preLoaderRoute: typeof ApiCustomerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding-upload': {
      id: '/api/branding-upload'
      path: '/api/branding-upload'
      fullPath: '/api/branding-upload'
      preLoaderRoute: typeof ApiBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/register': {
      id: '/_portal/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/login': {
      id: '/_portal/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant': {
      id: '/_portal/_tenant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalTenantRouteRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/register': {
      id: '/_admin/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminAdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/_tenant/rental/': {
      id: '/_portal/_tenant/rental/'
      path: '/rental'
      fullPath: '/rental/'
      preLoaderRoute: typeof PortalTenantRentalIndexRouteImport
      parentRoute: typeof PortalTenantRouteRoute
    }
    '/_portal/_tenant/order-confirmation/': {
      id: '/_portal/_tenant/order-confirmation/'
      path: '/order-confirmation'
      fullPath: '/order-confirmation/'
      preLoaderRoute: typeof PortalTenantOrderConfirmationIndexRouteImport
      parentRoute: typeof PortalTenantRouteRoute
    }
    '/_portal/_tenant/onboard/': {
      id: '/_portal/_tenant/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof PortalTenantOnboardIndexRouteImport
      parentRoute: typeof PortalTenantRouteRoute
    }
    '/_portal/_tenant/cart/': {
      id: '/_portal/_tenant/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof PortalTenantCartIndexRouteImport
      parentRoute: typeof PortalTenantRouteRoute
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/schedule/': {
      id: '/_admin/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule/'
      preLoaderRoute: typeof AdminDashboardScheduleIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/': {
      id: '/_admin/dashboard/promotions/'
      path: '/promotions'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof AdminDashboardPromotionsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/': {
      id: '/_admin/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/': {
      id: '/_admin/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof AdminDashboardLocationsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/': {
      id: '/_admin/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AdminDashboardCustomersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract': {
      id: '/api/orders/$orderId/contract'
      path: '/api/orders/$orderId/contract'
      fullPath: '/api/orders/$orderId/contract'
      preLoaderRoute: typeof ApiOrdersOrderIdContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-profiles/$customerProfileId/identity-document': {
      id: '/api/customer-profiles/$customerProfileId/identity-document'
      path: '/api/customer-profiles/$customerProfileId/identity-document'
      fullPath: '/api/customer-profiles/$customerProfileId/identity-document'
      preLoaderRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/auth/google/finalize': {
      id: '/_portal/auth/google/finalize'
      path: '/auth/google/finalize'
      fullPath: '/auth/google/finalize'
      preLoaderRoute: typeof PortalAuthGoogleFinalizeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard/promotions/new': {
      id: '/_admin/dashboard/promotions/new'
      path: '/promotions/new'
      fullPath: '/dashboard/promotions/new'
      preLoaderRoute: typeof AdminDashboardPromotionsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/$ownerId': {
      id: '/_admin/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/dashboard/owners/$ownerId'
      preLoaderRoute: typeof AdminDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId': {
      id: '/_admin/dashboard/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/$locationId': {
      id: '/_admin/dashboard/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/dashboard/locations/$locationId'
      preLoaderRoute: typeof AdminDashboardLocationsLocationIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/$customerId': {
      id: '/_admin/dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/assets/': {
      id: '/_admin/dashboard/inventory/assets/'
      path: '/inventory/assets'
      fullPath: '/dashboard/inventory/assets/'
      preLoaderRoute: typeof AdminDashboardInventoryAssetsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/': {
      id: '/_admin/dashboard/customers/pending-profiles/'
      path: '/customers/pending-profiles'
      fullPath: '/dashboard/customers/pending-profiles/'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/': {
      id: '/_admin/dashboard/catalog/products/'
      path: '/catalog/products'
      fullPath: '/dashboard/catalog/products/'
      preLoaderRoute: typeof AdminDashboardCatalogProductsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/': {
      id: '/_admin/dashboard/catalog/bundles/'
      path: '/catalog/bundles'
      fullPath: '/dashboard/catalog/bundles/'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract/download': {
      id: '/api/orders/$orderId/contract/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/contract/download'
      preLoaderRoute: typeof ApiOrdersOrderIdContractDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractRoute
    }
    '/_admin/dashboard/promotions/$promotionId/edit': {
      id: '/_admin/dashboard/promotions/$promotionId/edit'
      path: '/promotions/$promotionId/edit'
      fullPath: '/dashboard/promotions/$promotionId/edit'
      preLoaderRoute: typeof AdminDashboardPromotionsPromotionIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/$customerProfileId': {
      id: '/_admin/dashboard/customers/pending-profiles/$customerProfileId'
      path: '/customers/pending-profiles/$customerProfileId'
      fullPath: '/dashboard/customers/pending-profiles/$customerProfileId'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesCustomerProfileIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/new': {
      id: '/_admin/dashboard/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/dashboard/catalog/products/new'
      preLoaderRoute: typeof AdminDashboardCatalogProductsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/new': {
      id: '/_admin/dashboard/catalog/bundles/new'
      path: '/catalog/bundles/new'
      fullPath: '/dashboard/catalog/bundles/new'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/$productId/': {
      id: '/_admin/dashboard/catalog/products/$productId/'
      path: '/catalog/products/$productId'
      fullPath: '/dashboard/catalog/products/$productId/'
      preLoaderRoute: typeof AdminDashboardCatalogProductsProductIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/$bundleId/': {
      id: '/_admin/dashboard/catalog/bundles/$bundleId/'
      path: '/catalog/bundles/$bundleId'
      fullPath: '/dashboard/catalog/bundles/$bundleId/'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesBundleIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/$productId/edit': {
      id: '/_admin/dashboard/catalog/products/$productId/edit'
      path: '/catalog/products/$productId/edit'
      fullPath: '/dashboard/catalog/products/$productId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogProductsProductIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/$bundleId/edit': {
      id: '/_admin/dashboard/catalog/bundles/$bundleId/edit'
      path: '/catalog/bundles/$bundleId/edit'
      fullPath: '/dashboard/catalog/bundles/$bundleId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesBundleIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface PortalTenantRouteRouteChildren {
  PortalTenantCartIndexRoute: typeof PortalTenantCartIndexRoute
  PortalTenantOnboardIndexRoute: typeof PortalTenantOnboardIndexRoute
  PortalTenantOrderConfirmationIndexRoute: typeof PortalTenantOrderConfirmationIndexRoute
  PortalTenantRentalIndexRoute: typeof PortalTenantRentalIndexRoute
}

const PortalTenantRouteRouteChildren: PortalTenantRouteRouteChildren = {
  PortalTenantCartIndexRoute: PortalTenantCartIndexRoute,
  PortalTenantOnboardIndexRoute: PortalTenantOnboardIndexRoute,
  PortalTenantOrderConfirmationIndexRoute:
    PortalTenantOrderConfirmationIndexRoute,
  PortalTenantRentalIndexRoute: PortalTenantRentalIndexRoute,
}

const PortalTenantRouteRouteWithChildren =
  PortalTenantRouteRoute._addFileChildren(PortalTenantRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalTenantRouteRoute: typeof PortalTenantRouteRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalAuthGoogleFinalizeRoute: typeof PortalAuthGoogleFinalizeRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalTenantRouteRoute: PortalTenantRouteRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalAuthGoogleFinalizeRoute: PortalAuthGoogleFinalizeRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardCustomersCustomerIdRoute: typeof AdminDashboardCustomersCustomerIdRoute
  AdminDashboardLocationsLocationIdRoute: typeof AdminDashboardLocationsLocationIdRoute
  AdminDashboardOrdersOrderIdRoute: typeof AdminDashboardOrdersOrderIdRoute
  AdminDashboardOwnersOwnerIdRoute: typeof AdminDashboardOwnersOwnerIdRoute
  AdminDashboardPromotionsNewRoute: typeof AdminDashboardPromotionsNewRoute
  AdminDashboardCustomersIndexRoute: typeof AdminDashboardCustomersIndexRoute
  AdminDashboardLocationsIndexRoute: typeof AdminDashboardLocationsIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardPromotionsIndexRoute: typeof AdminDashboardPromotionsIndexRoute
  AdminDashboardScheduleIndexRoute: typeof AdminDashboardScheduleIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardCatalogBundlesNewRoute: typeof AdminDashboardCatalogBundlesNewRoute
  AdminDashboardCatalogProductsNewRoute: typeof AdminDashboardCatalogProductsNewRoute
  AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute: typeof AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute
  AdminDashboardPromotionsPromotionIdEditRoute: typeof AdminDashboardPromotionsPromotionIdEditRoute
  AdminDashboardCatalogBundlesIndexRoute: typeof AdminDashboardCatalogBundlesIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCatalogProductsIndexRoute: typeof AdminDashboardCatalogProductsIndexRoute
  AdminDashboardCustomersPendingProfilesIndexRoute: typeof AdminDashboardCustomersPendingProfilesIndexRoute
  AdminDashboardInventoryAssetsIndexRoute: typeof AdminDashboardInventoryAssetsIndexRoute
  AdminDashboardCatalogBundlesBundleIdEditRoute: typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  AdminDashboardCatalogProductsProductIdEditRoute: typeof AdminDashboardCatalogProductsProductIdEditRoute
  AdminDashboardCatalogBundlesBundleIdIndexRoute: typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  AdminDashboardCatalogProductsProductIdIndexRoute: typeof AdminDashboardCatalogProductsProductIdIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardCustomersCustomerIdRoute:
    AdminDashboardCustomersCustomerIdRoute,
  AdminDashboardLocationsLocationIdRoute:
    AdminDashboardLocationsLocationIdRoute,
  AdminDashboardOrdersOrderIdRoute: AdminDashboardOrdersOrderIdRoute,
  AdminDashboardOwnersOwnerIdRoute: AdminDashboardOwnersOwnerIdRoute,
  AdminDashboardPromotionsNewRoute: AdminDashboardPromotionsNewRoute,
  AdminDashboardCustomersIndexRoute: AdminDashboardCustomersIndexRoute,
  AdminDashboardLocationsIndexRoute: AdminDashboardLocationsIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardPromotionsIndexRoute: AdminDashboardPromotionsIndexRoute,
  AdminDashboardScheduleIndexRoute: AdminDashboardScheduleIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardCatalogBundlesNewRoute: AdminDashboardCatalogBundlesNewRoute,
  AdminDashboardCatalogProductsNewRoute: AdminDashboardCatalogProductsNewRoute,
  AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute:
    AdminDashboardCustomersPendingProfilesCustomerProfileIdRoute,
  AdminDashboardPromotionsPromotionIdEditRoute:
    AdminDashboardPromotionsPromotionIdEditRoute,
  AdminDashboardCatalogBundlesIndexRoute:
    AdminDashboardCatalogBundlesIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCatalogProductsIndexRoute:
    AdminDashboardCatalogProductsIndexRoute,
  AdminDashboardCustomersPendingProfilesIndexRoute:
    AdminDashboardCustomersPendingProfilesIndexRoute,
  AdminDashboardInventoryAssetsIndexRoute:
    AdminDashboardInventoryAssetsIndexRoute,
  AdminDashboardCatalogBundlesBundleIdEditRoute:
    AdminDashboardCatalogBundlesBundleIdEditRoute,
  AdminDashboardCatalogProductsProductIdEditRoute:
    AdminDashboardCatalogProductsProductIdEditRoute,
  AdminDashboardCatalogBundlesBundleIdIndexRoute:
    AdminDashboardCatalogBundlesBundleIdIndexRoute,
  AdminDashboardCatalogProductsProductIdIndexRoute:
    AdminDashboardCatalogProductsProductIdIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface ApiOrdersOrderIdContractRouteChildren {
  ApiOrdersOrderIdContractDownloadRoute: typeof ApiOrdersOrderIdContractDownloadRoute
}

const ApiOrdersOrderIdContractRouteChildren: ApiOrdersOrderIdContractRouteChildren =
  {
    ApiOrdersOrderIdContractDownloadRoute:
      ApiOrdersOrderIdContractDownloadRoute,
  }

const ApiOrdersOrderIdContractRouteWithChildren =
  ApiOrdersOrderIdContractRoute._addFileChildren(
    ApiOrdersOrderIdContractRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  ApiBrandingUploadRoute: ApiBrandingUploadRoute,
  ApiCustomerUploadRoute: ApiCustomerUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminRegisterRoute: AdminAdminRegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute:
    ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute,
  ApiOrdersOrderIdContractRoute: ApiOrdersOrderIdContractRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
