export interface BundleComponentProps {
  productId: string;
  quantity: number;
}

/**
 * Value object representing a product slot in a bundle.
 * Identity is determined by productId — a product can appear at most once per bundle.
 * The quantity field expresses how many units of that product are required per bundle instance.
 *
 * No domain id. The surrogate key on the persistence layer is generated by the mapper.
 */
export class BundleComponent {
  private readonly _productId: string;
  private readonly _quantity: number;

  private constructor(props: BundleComponentProps) {
    this._productId = props.productId;
    this._quantity = props.quantity;
  }

  public static create(props: BundleComponentProps): BundleComponent {
    BundleComponent.assertValidQuantity(props.quantity);
    return new BundleComponent(props);
  }

  // --- Getters ---
  get productId(): string {
    return this._productId;
  }

  get quantity(): number {
    return this._quantity;
  }

  public equals(other: BundleComponent): boolean {
    return this._productId === other._productId;
  }

  // --- Guards ---
  private static assertValidQuantity(quantity: number): void {
    if (!Number.isInteger(quantity) || quantity <= 0) {
      throw new Error(`quantity must be a positive integer, received: ${quantity}`);
    }
  }
}
