export enum NotificationType {
  ORDER_CREATED_CONFIRMATION = 'ORDER_CREATED_CONFIRMATION',
  ORDER_CREATED_BY_CUSTOMER = 'ORDER_CREATED_BY_CUSTOMER',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
