export enum NotificationType {
  ORDER_CREATED_CONFIRMATION = 'ORDER_CREATED_CONFIRMATION',
  ORDER_CREATED_BY_CUSTOMER = 'ORDER_CREATED_BY_CUSTOMER',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  DOCUMENT_SIGNING_INVITATION = 'DOCUMENT_SIGNING_INVITATION',
  DOCUMENT_SIGNING_FINAL_COPY = 'DOCUMENT_SIGNING_FINAL_COPY',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
